In [68]:
import pandas as pd

In [69]:
tree_data = pd.read_csv(r'..\Data\new_york_tree_census_2015.csv')
tree_data['zipcode'].unique()

array([11366, 11370, 11434, 11209, 11692, 10031, 11207, 11219, 11421,
       10474, 11419, 10308, 10001, 10312, 11221, 10464, 11234, 10305,
       11201, 11233, 11411, 11220, 10009, 11372, 11432, 10314, 10461,
       10309, 11367, 11205, 10025, 11374, 11105, 11217, 10458, 11001,
       10459, 11364, 11379, 11691, 11004, 10032, 11358, 11238, 11213,
       11249, 10470, 11356, 11103, 11361, 10007, 11385, 11355, 11230,
       10469, 10468, 11426, 10304, 10456, 10463, 11206, 10462, 11216,
       11208, 10465, 11375, 11429, 11365, 11435, 11218, 10034, 11414,
       11412, 11377, 11223, 11427, 11204, 11357, 10022, 11215, 11428,
       10036, 10024, 10467, 10026, 11420, 11423, 10038, 11231, 11369,
       11413, 10453, 11210, 11436, 10307, 10475, 11229, 11363, 11040,
       10003, 10457, 11378, 11212, 11373, 10014, 11360, 11418, 11226,
       10301, 10473, 10472, 11235, 11225, 10302, 11422, 11354, 11236,
       11106, 10013, 11214, 10452, 10466, 10012, 11203,    83, 10310,
       11694, 10002, 11224, 10035, 10471, 10306, 11415, 11222, 10303,
       11368, 10016, 10451, 11433, 11239, 10021, 10018, 11237, 11211,
       10017, 10029, 10128, 11102, 10011, 11104, 11693, 10019, 10006,
       11228, 10040, 10455, 10010, 11362, 10028, 10033, 10454, 11101,
       10023, 10065, 10075, 10460, 11371, 10037, 11416, 10027, 10004,
       11232, 10039, 10030, 11417, 10020, 11109, 10281, 11251, 10069,
       10280, 10005, 11430, 10282, 11005, 11697, 10111, 11096, 11451,
       10115, 10048], dtype=int64)

In [70]:
tree_data_small = tree_data[['tree_dbh', 'curb_loc', 'status', 'health', 'spc_common', 'sidewalk', 'zipcode']].copy()
tree_data_small.head()

   tree_dbh curb_loc status health              spc_common  sidewalk  zipcode
0        10   OnCurb  Alive   Good               green ash  NoDamage    11366
1         9   OnCurb  Alive   Good             honeylocust  NoDamage    11370
2         7   OnCurb  Alive   Good            Callery pear  NoDamage    11434
3        10   OnCurb  Alive   Good            Callery pear  NoDamage    11209
4         4   OnCurb  Alive   Good  'Schubert' chokecherry  NoDamage    11692

In [71]:
# initial clean of the data - drop na
tree_data_small.dropna(inplace=True)

tree_data_small.info()

<class 'pandas.core.frame.DataFrame'>
Index: 652166 entries, 0 to 683787
Data columns (total 7 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   tree_dbh    652166 non-null  int64
 1   curb_loc    652166 non-null  object
 2   status      652166 non-null  object
 3   health      652166 non-null  object
 4   spc_common  652166 non-null  object
 5   sidewalk    652166 non-null  object
 6   zipcode     652166 non-null  int64
dtypes: int64(2), object(5)
memory usage: 39.8+ MB

In [72]:
def get_ratio(series):
       val_counts = series.value_counts()
       if len(val_counts) > 1:
              return val_counts.iloc[0]/ val_counts.iloc[1]
       # if there is only one value then the ratio is 1
       return 1

def get_top_3(df, zip_col_name, split_col_name):
       # '''
       # Takes in the full dataframe and returns a dataframe of zip code and the top 3 most common values for split_col_name 
       # :param series: 
       # :return: 
       # '''
       df.groupby(zip_col_name)
       val_counts = df[split_col_name].value_counts()
       ret_df = df[zip_col_name]
       if len(val_counts) >= 3:
              ret_df[split_col_name + '1'] = val_counts[0]
              ret_df[split_col_name + '2'] = val_counts[1]
              ret_df[split_col_name + '3'] = val_counts[2]
           
def get_first(series):
       val_counts = series.value_counts()
       return val_counts.index[0]

def get_second(series):
       val_counts = series.value_counts()
       if len(val_counts) > 1:
              return val_counts.index[1]
       else:
              return val_counts.index[-1]

def get_third(series):
       val_counts = series.value_counts()
       if len(val_counts) > 2:
              return val_counts.index[2]
       else:
              return val_counts.index[-1]
       
def count_unique_vals(series):
       return series.value_counts().to_dict()

In [73]:
# because we are going to join on zip code, we need to make meaningful aggregates for each column per zip code
tree_data_final = tree_data_small.groupby('zipcode').agg(
       dbh_mean=('tree_dbh', 'mean'),
       curb_ratio=('curb_loc', get_ratio),
       status_ratio=('status', get_ratio),
       sidewalk_ratio=('sidewalk', get_ratio),
       health_counts=('health', count_unique_vals),
       species_1=('spc_common', get_first),
       species_2=('spc_common', get_second),
       species_3=('spc_common', get_third)                          
).reset_index()

health_counts_df = pd.DataFrame(tree_data_final['health_counts'].tolist()).fillna(0).astype(int)
tree_data_final = pd.concat([tree_data_final, health_counts_df], axis=1).drop(columns=['health_counts'])

tree_data_final

,zipcode,dbh_mean,curb_ratio,status_ratio,sidewalk_ratio,species_1,species_2,species_3,Good,Fair,Poor
0,83,16.505365,1.273171,1,3.217195,American elm,pin oak,ginkgo,885,39,8
1,10001,7.365882,46.222222,1,4.629139,honeylocust,Callery pear,Japanese zelkova,719,100,31
2,10002,8.459222,5.255072,1,4.678947,London planetree,honeylocust,ginkgo,1656,387,115
3,10003,9.077200,91.523810,1,2.672968,honeylocust,Callery pear,ginkgo,1480,361,102
4,10004,6.658120,3.178571,1,28.250000,honeylocust,ginkgo,Japanese zelkova,97,17,3
...,...,...,...,...,...,...,...,...,...,...,...
186,11691,8.813316,27.221053,1,4.432624,honeylocust,London planetree,cherry,3761,1258,343
187,11692,4.962963,12.027972,1,5.900000,Callery pear,cherry,Sophora,1122,523,218
188,11693,7.897335,6.914062,1,12.876712,London planetree,honeylocust,Callery pear,518,288,207
189,11694,8.053841,17.358382,1,6.234624,honeylocust,Callery pear,cherry,1958,833,385
190,11697,4.666667,1.000000,1,1.000000,honeylocust,ginkgo,Siberian elm,0,8,16

In [74]:
crime_data = pd.read_csv(r'..\Data\2015_Crime.csv', low_memory=False)

In [75]:
crime_data.head()

,Ticket Number,Violation Date,Violation Time,Issuing Agency,Respondent First Name,Respondent Last Name,Balance Due,Violation Location (Borough),Violation Location (Block No.),Violation Location (Lot No.),...,Charge #8: Code Description,Charge #8: Infraction Amount,Charge #9: Code,Charge #9: Code Section,Charge #9: Code Description,Charge #9: Infraction Amount,Charge #10: Code,Charge #10: Code Section,Charge #10: Code Description,Charge #10: Infraction Amount
0,0187818290,06/30/2015,07:50:00,SANITATION OTHERS,NaN,607 2 AVE RE,0.0,MANHATTAN,914.0,28.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1276215F1,06/30/2015,NaN,DOHMH - BFSCS,NaN,JEM PROVISIONS INC,NaN,BROOKLYN,NaN,NaN,...,Toilet facility not properly supplied in that ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0700053870,06/30/2015,13:54:00,DEPT OF TRAN,NaN,CONSOLIDATED EDISON,NaN,QUEENS,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0700051990,06/30/2015,14:10:00,DEPT OF TRAN,NaN,CONSOLIDATED EDISON,NaN,QUEENS,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0700051981,06/30/2015,14:04:00,DEPT OF TRANSPORTATION,NaN,CONSOLIDATED EDISON,NaN,QUEENS,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [76]:
crime_data.columns

Index(['Ticket Number', 'Violation Date', 'Violation Time', 'Issuing Agency',
       'Respondent First Name', 'Respondent Last Name', 'Balance Due',
       'Violation Location (Borough)', 'Violation Location (Block No.)',
       'Violation Location (Lot No.)', 'Violation Location (House #)',
       'Violation Location (Street Name)', 'Violation Location (Floor)',
       'Violation Location (City)', 'Violation Location (Zip Code)',
       'Violation Location (State Name)', 'Respondent Address (Borough)',
       'Respondent Address (House #)', 'Respondent Address (Street Name)',
       'Respondent Address (City)', 'Respondent Address (Zip Code)',
       'Respondent Address (State Name)', 'Hearing Status', 'Hearing Result',
       'Scheduled Hearing Location', 'Hearing Date', 'Hearing Time',
       'Decision Location (Borough)', 'Decision Date',
       'Total Violation Amount', 'Violation Details', 'Date Judgment Docketed',
       'Respondent Address or Facility Number(For FDNY and DOB Tickets)',
       'Penalty Imposed', 'Paid Amount', 'Additional Penalties or Late Fees',
       'Compliance Status', 'Violation Description', 'Charge #1: Code',
       'Charge #1: Code Section', 'Charge #1: Code Description',
       'Charge #1: Infraction Amount', 'Charge #2: Code',
       'Charge #2: Code Section', 'Charge #2: Code Description',
       'Charge #2: Infraction Amount', 'Charge #3: Code',
       'Charge #3: Code Section', 'Charge #3: Code Description',
       'Charge #3: Infraction Amount', 'Charge #4: Code',
       'Charge #4: Code Section', 'Charge #4: Code Description',
       'Charge #4: Infraction Amount', 'Charge #5: Code',
       'Charge #5: Code Section', 'Charge #5: Code Description',
       'Charge #5: Infraction Amount', 'Charge #6: Code',
       'Charge #6: Code Section', 'Charge #6: Code Description',
       'Charge #6: Infraction Amount', 'Charge #7: Code',
       'Charge #7: Code Section', 'Charge #7: Code Description',
       'Charge #7: Infraction Amount', 'Charge #8: Code',
       'Charge #8: Code Section', 'Charge #8: Code Description',
       'Charge #8: Infraction Amount', 'Charge #9: Code',
       'Charge #9: Code Section', 'Charge #9: Code Description',
       'Charge #9: Infraction Amount', 'Charge #10: Code',
       'Charge #10: Code Section', 'Charge #10: Code Description',
       'Charge #10: Infraction Amount'],
      dtype='object')

In [77]:
crime_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750352 entries, 0 to 750351
Data columns (total 78 columns):
 #   Column                                                           Non-Null Count   Dtype
---  ------                                                           --------------   -----
 0   Ticket Number                                                    750352 non-null  object
 1   Violation Date                                                   750352 non-null  object
 2   Violation Time                                                   611192 non-null  object
 3   Issuing Agency                                                   631478 non-null  object
 4   Respondent First Name                                            348156 non-null  object
 5   Respondent Last Name                                             701497 non-null  object
 6   Balance Due                                                      188781 non-null  float64
 7   Violation Location (Borough)                                     750174 non-null  object
 8   Violation Location (Block No.)                                   553865 non-null  float64
 9   Violation Location (Lot No.)                                     553862 non-null  float64
 10  Violation Location (House #)                                     574440 non-null  object
 11  Violation Location (Street Name)                                 609064 non-null  object
 12  Violation Location (Floor)                                       0 non-null       float64
 13  Violation Location (City)                                        746553 non-null  object
 14  Violation Location (Zip Code)                                    712934 non-null  object
 15  Violation Location (State Name)                                  608048 non-null  object
 16  Respondent Address (Borough)                                     722665 non-null  object
 17  Respondent Address (House #)                                     635149 non-null  object
 18  Respondent Address (Street Name)                                 637034 non-null  object
 19  Respondent Address (City)                                        589957 non-null  object
 20  Respondent Address (Zip Code)                                    588137 non-null  object
 21  Respondent Address (State Name)                                  589829 non-null  object
 22  Hearing Status                                                   611192 non-null  object
 23  Hearing Result                                                   459212 non-null  object
 24  Scheduled Hearing Location                                       610464 non-null  object
 25  Hearing Date                                                     750170 non-null  object
 26  Hearing Time                                                     649036 non-null  object
 27  Decision Location (Borough)                                      161624 non-null  object
 28  Decision Date                                                    567917 non-null  object
 29  Total Violation Amount                                           712441 non-null  float64
 30  Violation Details                                                668429 non-null  object
 31  Date Judgment Docketed                                           130569 non-null  object
 32  Respondent Address or Facility Number(For FDNY and DOB Tickets)  154563 non-null  object
 33  Penalty Imposed                                                  659738 non-null  float64
 34  Paid Amount                                                      627566 non-null  float64
 35  Additional Penalties or Late Fees                                311229 non-null  float64
 36  Compliance Status                                                193953 non-null  object
 37  Violation Description                                            35369 non-null   object
 38  Charge #1: Code                                                  739105 non-null  object
 39  Charge #1: Code Section                                          739066 non-null  object
 40  Charge #1: Code Description                                      637791 non-null  object
 41  Charge #1: Infraction Amount                                     711305 non-null  float64
 42  Charge #2: Code                                                  54411 non-null   object
 43  Charge #2: Code Section                                          54404 non-null   object
 44  Charge #2: Code Description                                      45014 non-null   object
 45  Charge #2: Infraction Amount                                     26715 non-null   float64
 46  Charge #3: Code                                                  38460 non-null   object
 47  Charge #3: Code Section                                          38460 non-null   object
 48  Charge #3: Code Description                                      30075 non-null   object
 49  Charge #3: Infraction Amount                                     13157 non-null   float64
 50  Charge #4: Code                                                  35707 non-null   object
 51  Charge #4: Code Section                                          35707 non-null   object
 52  Charge #4: Code Description                                      27385 non-null   object
 53  Charge #4: Infraction Amount                                     10405 non-null   float64
 54  Charge #5: Code                                                  28199 non-null   object
 55  Charge #5: Code Section                                          28199 non-null   object
 56  Charge #5: Code Description                                      25047 non-null   object
 57  Charge #5: Infraction Amount                                     4046 non-null    float64
 58  Charge #6: Code                                                  27661 non-null   object
 59  Charge #6: Code Section                                          27661 non-null   object
 60  Charge #6: Code Description                                      24531 non-null   object
 61  Charge #6: Infraction Amount                                     3514 non-null    float64
 62  Charge #7: Code                                                  24823 non-null   object
 63  Charge #7: Code Section                                          24823 non-null   object
 64  Charge #7: Code Description                                      21723 non-null   object
 65  Charge #7: Infraction Amount                                     3272 non-null    float64
 66  Charge #8: Code                                                  24631 non-null   object
 67  Charge #8: Code Section                                          24631 non-null   object
 68  Charge #8: Code Description                                      21599 non-null   object
 69  Charge #8: Infraction Amount                                     3083 non-null    float64
 70  Charge #9: Code                                                  19470 non-null   object
 71  Charge #9: Code Section                                          19470 non-null   object
 72  Charge #9: Code Description                                      16463 non-null   object
 73  Charge #9: Infraction Amount                                     3027 non-null    float64
 74  Charge #10: Code                                                 17539 non-null   object
 75  Charge #10: Code Section                                         17539 non-null   object
 76  Charge #10: Code Description                                     16450 non-null   object
 77  Charge #10: Infraction Amount                                    1096 non-null    float64
dtypes: float64(18), object(60)
memory usage: 446.5+ MB

In [78]:
crime_data = crime_data.dropna(subset=['Ticket Number', 'Violation Date', 'Violation Time', 'Issuing Agency',
       'Respondent First Name', 'Respondent Last Name', 'Balance Due',
       'Violation Location (Borough)', 'Violation Location (Block No.)',
       'Violation Location (Lot No.)', 'Violation Location (House #)',
       'Violation Location (Street Name)', 'Violation Location (Floor)',
       'Violation Location (City)', 'Violation Location (Zip Code)',
       'Violation Location (State Name)', 'Respondent Address (Borough)',
       'Respondent Address (House #)', 'Respondent Address (Street Name)',
       'Respondent Address (City)', 'Respondent Address (Zip Code)',
       'Respondent Address (State Name)', 'Hearing Status', 'Hearing Result',
       'Scheduled Hearing Location', 'Hearing Date', 'Hearing Time',
       'Decision Location (Borough)', 'Decision Date',
       'Total Violation Amount', 'Violation Details', 'Date Judgment Docketed',
       'Respondent Address or Facility Number(For FDNY and DOB Tickets)',
       'Penalty Imposed', 'Paid Amount', 'Additional Penalties or Late Fees',
       'Compliance Status', 'Violation Description', 'Charge #1: Code',
       'Charge #1: Code Section', 'Charge #1: Code Description',
       'Charge #1: Infraction Amount', 'Charge #2: Code',
       'Charge #2: Code Section', 'Charge #2: Code Description',
       'Charge #2: Infraction Amount', 'Charge #3: Code',
       'Charge #3: Code Section', 'Charge #3: Code Description',
       'Charge #3: Infraction Amount', 'Charge #4: Code',
       'Charge #4: Code Section', 'Charge #4: Code Description',
       'Charge #4: Infraction Amount', 'Charge #5: Code',
       'Charge #5: Code Section', 'Charge #5: Code Description',
       'Charge #5: Infraction Amount', 'Charge #6: Code',
       'Charge #6: Code Section', 'Charge #6: Code Description',
       'Charge #6: Infraction Amount', 'Charge #7: Code',
       'Charge #7: Code Section', 'Charge #7: Code Description',
       'Charge #7: Infraction Amount', 'Charge #8: Code',
       'Charge #8: Code Section', 'Charge #8: Code Description',
       'Charge #8: Infraction Amount', 'Charge #9: Code',
       'Charge #9: Code Section', 'Charge #9: Code Description',
       'Charge #9: Infraction Amount', 'Charge #10: Code',
       'Charge #10: Code Section', 'Charge #10: Code Description',
       'Charge #10: Infraction Amount'])

In [79]:
crime_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 78 columns):
 #   Column                                                           Non-Null Count  Dtype
---  ------                                                           --------------  -----
 0   Ticket Number                                                    0 non-null      object
 1   Violation Date                                                   0 non-null      object
 2   Violation Time                                                   0 non-null      object
 3   Issuing Agency                                                   0 non-null      object
 4   Respondent First Name                                            0 non-null      object
 5   Respondent Last Name                                             0 non-null      object
 6   Balance Due                                                      0 non-null      float64
 7   Violation Location (Borough)                                     0 non-null      object
 8   Violation Location (Block No.)                                   0 non-null      float64
 9   Violation Location (Lot No.)                                     0 non-null      float64
 10  Violation Location (House #)                                     0 non-null      object
 11  Violation Location (Street Name)                                 0 non-null      object
 12  Violation Location (Floor)                                       0 non-null      float64
 13  Violation Location (City)                                        0 non-null      object
 14  Violation Location (Zip Code)                                    0 non-null      object
 15  Violation Location (State Name)                                  0 non-null      object
 16  Respondent Address (Borough)                                     0 non-null      object
 17  Respondent Address (House #)                                     0 non-null      object
 18  Respondent Address (Street Name)                                 0 non-null      object
 19  Respondent Address (City)                                        0 non-null      object
 20  Respondent Address (Zip Code)                                    0 non-null      object
 21  Respondent Address (State Name)                                  0 non-null      object
 22  Hearing Status                                                   0 non-null      object
 23  Hearing Result                                                   0 non-null      object
 24  Scheduled Hearing Location                                       0 non-null      object
 25  Hearing Date                                                     0 non-null      object
 26  Hearing Time                                                     0 non-null      object
 27  Decision Location (Borough)                                      0 non-null      object
 28  Decision Date                                                    0 non-null      object
 29  Total Violation Amount                                           0 non-null      float64
 30  Violation Details                                                0 non-null      object
 31  Date Judgment Docketed                                           0 non-null      object
 32  Respondent Address or Facility Number(For FDNY and DOB Tickets)  0 non-null      object
 33  Penalty Imposed                                                  0 non-null      float64
 34  Paid Amount                                                      0 non-null      float64
 35  Additional Penalties or Late Fees                                0 non-null      float64
 36  Compliance Status                                                0 non-null      object
 37  Violation Description                                            0 non-null      object
 38  Charge #1: Code                                                  0 non-null      object
 39  Charge #1: Code Section                                          0 non-null      object
 40  Charge #1: Code Description                                      0 non-null      object
 41  Charge #1: Infraction Amount                                     0 non-null      float64
 42  Charge #2: Code                                                  0 non-null      object
 43  Charge #2: Code Section                                          0 non-null      object
 44  Charge #2: Code Description                                      0 non-null      object
 45  Charge #2: Infraction Amount                                     0 non-null      float64
 46  Charge #3: Code                                                  0 non-null      object
 47  Charge #3: Code Section                                          0 non-null      object
 48  Charge #3: Code Description                                      0 non-null      object
 49  Charge #3: Infraction Amount                                     0 non-null      float64
 50  Charge #4: Code                                                  0 non-null      object
 51  Charge #4: Code Section                                          0 non-null      object
 52  Charge #4: Code Description                                      0 non-null      object
 53  Charge #4: Infraction Amount                                     0 non-null      float64
 54  Charge #5: Code                                                  0 non-null      object
 55  Charge #5: Code Section                                          0 non-null      object
 56  Charge #5: Code Description                                      0 non-null      object
 57  Charge #5: Infraction Amount                                     0 non-null      float64
 58  Charge #6: Code                                                  0 non-null      object
 59  Charge #6: Code Section                                          0 non-null      object
 60  Charge #6: Code Description                                      0 non-null      object
 61  Charge #6: Infraction Amount                                     0 non-null      float64
 62  Charge #7: Code                                                  0 non-null      object
 63  Charge #7: Code Section                                          0 non-null      object
 64  Charge #7: Code Description                                      0 non-null      object
 65  Charge #7: Infraction Amount                                     0 non-null      float64
 66  Charge #8: Code                                                  0 non-null      object
 67  Charge #8: Code Section                                          0 non-null      object
 68  Charge #8: Code Description                                      0 non-null      object
 69  Charge #8: Infraction Amount                                     0 non-null      float64
 70  Charge #9: Code                                                  0 non-null      object
 71  Charge #9: Code Section                                          0 non-null      object
 72  Charge #9: Code Description                                      0 non-null      object
 73  Charge #9: Infraction Amount                                     0 non-null      float64
 74  Charge #10: Code                                                 0 non-null      object
 75  Charge #10: Code Section                                         0 non-null      object
 76  Charge #10: Code Description                                     0 non-null      object
 77  Charge #10: Infraction Amount                                    0 non-null      float64
dtypes: float64(18), object(60)
memory usage: 0.0+ bytes