In [1]:
import pandas as pd

In [2]:
tree_data = pd.read_csv(r'D:\VTacademics\sem3\urbanComputing\final_project\urban-computing\Data\new_york_tree_census_2015.csv')

In [3]:
tree_data.head()

,tree_id,block_id,created_at,tree_dbh,stump_diam,curb_loc,status,health,spc_latin,spc_common,...,st_assem,st_senate,nta,nta_name,boro_ct,state,latitude,longitude,x_sp,y_sp
0,606945,305778,2016-06-28,10,0,OnCurb,Alive,Good,Fraxinus pennsylvanica,green ash,...,25,14,QN37,Kew Gardens Hills,4125700,New York,40.724339,-73.805180,1.038250e+06,203232.9417
1,160321,341273,2015-08-19,9,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,honeylocust,...,34,13,QN28,Jackson Heights,4030902,New York,40.756626,-73.894167,1.013571e+06,214953.6472
2,541347,325281,2015-12-30,7,0,OnCurb,Alive,Good,Pyrus calleryana,Callery pear,...,32,10,QN76,Baisley Park,4028800,New York,40.679777,-73.788463,1.042923e+06,187008.2671
3,613930,203822,2016-07-05,10,0,OnCurb,Alive,Good,Pyrus calleryana,Callery pear,...,46,22,BK31,Bay Ridge,3005000,New York,40.622743,-74.037543,9.738279e+05,166160.5847
4,18353,338911,2015-06-13,4,0,OnCurb,Alive,Good,Prunus virginiana,'Schubert' chokecherry,...,31,10,QN12,Hammels-Arverne-Edgemere,4095400,New York,40.596514,-73.797622,1.040452e+06,156667.5017

In [4]:
tree_data.columns

Index(['tree_id', 'block_id', 'created_at', 'tree_dbh', 'stump_diam',
       'curb_loc', 'status', 'health', 'spc_latin', 'spc_common', 'steward',
       'guards', 'sidewalk', 'user_type', 'problems', 'root_stone',
       'root_grate', 'root_other', 'trunk_wire', 'trnk_light', 'trnk_other',
       'brch_light', 'brch_shoe', 'brch_other', 'address', 'zipcode',
       'zip_city', 'cb_num', 'borocode', 'boroname', 'cncldist', 'st_assem',
       'st_senate', 'nta', 'nta_name', 'boro_ct', 'state', 'latitude',
       'longitude', 'x_sp', 'y_sp'],
      dtype='object')

In [5]:
tree_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683788 entries, 0 to 683787
Data columns (total 41 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   tree_id     683788 non-null  int64
 1   block_id    683788 non-null  int64
 2   created_at  683788 non-null  object
 3   tree_dbh    683788 non-null  int64
 4   stump_diam  683788 non-null  int64
 5   curb_loc    683788 non-null  object
 6   status      683788 non-null  object
 7   health      652172 non-null  object
 8   spc_latin   652169 non-null  object
 9   spc_common  652169 non-null  object
 10  steward     652173 non-null  object
 11  guards      652172 non-null  object
 12  sidewalk    652172 non-null  object
 13  user_type   683788 non-null  object
 14  problems    652124 non-null  object
 15  root_stone  683788 non-null  object
 16  root_grate  683788 non-null  object
 17  root_other  683788 non-null  object
 18  trunk_wire  683788 non-null  object
 19  trnk_light  683788 non-null  object
 20  trnk_other  683788 non-null  object
 21  brch_light  683788 non-null  object
 22  brch_shoe   683788 non-null  object
 23  brch_other  683788 non-null  object
 24  address     683788 non-null  object
 25  zipcode     683788 non-null  int64
 26  zip_city    683788 non-null  object
 27  cb_num      683788 non-null  int64
 28  borocode    683788 non-null  int64
 29  boroname    683788 non-null  object
 30  cncldist    683788 non-null  int64
 31  st_assem    683788 non-null  int64
 32  st_senate   683788 non-null  int64
 33  nta         683788 non-null  object
 34  nta_name    683788 non-null  object
 35  boro_ct     683788 non-null  int64
 36  state       683788 non-null  object
 37  latitude    683788 non-null  float64
 38  longitude   683788 non-null  float64
 39  x_sp        683788 non-null  float64
 40  y_sp        683788 non-null  float64
dtypes: float64(4), int64(11), object(26)
memory usage: 213.9+ MB

In [6]:
tree_data = tree_data.dropna(subset=[
    'tree_id', 'block_id', 'created_at', 'tree_dbh', 'stump_diam',
    'curb_loc', 'status', 'health', 'spc_latin', 'spc_common', 'steward',
    'guards', 'sidewalk', 'user_type', 'problems', 'root_stone',
    'root_grate', 'root_other', 'trunk_wire', 'trnk_light', 'trnk_other',
    'brch_light', 'brch_shoe', 'brch_other', 'address', 'zipcode',
    'zip_city', 'cb_num', 'borocode', 'boroname', 'cncldist', 'st_assem',
    'st_senate', 'nta', 'nta_name', 'boro_ct', 'state', 'latitude',
    'longitude', 'x_sp', 'y_sp'
])

In [7]:
tree_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 652118 entries, 0 to 683787
Data columns (total 41 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   tree_id     652118 non-null  int64
 1   block_id    652118 non-null  int64
 2   created_at  652118 non-null  object
 3   tree_dbh    652118 non-null  int64
 4   stump_diam  652118 non-null  int64
 5   curb_loc    652118 non-null  object
 6   status      652118 non-null  object
 7   health      652118 non-null  object
 8   spc_latin   652118 non-null  object
 9   spc_common  652118 non-null  object
 10  steward     652118 non-null  object
 11  guards      652118 non-null  object
 12  sidewalk    652118 non-null  object
 13  user_type   652118 non-null  object
 14  problems    652118 non-null  object
 15  root_stone  652118 non-null  object
 16  root_grate  652118 non-null  object
 17  root_other  652118 non-null  object
 18  trunk_wire  652118 non-null  object
 19  trnk_light  652118 non-null  object
 20  trnk_other  652118 non-null  object
 21  brch_light  652118 non-null  object
 22  brch_shoe   652118 non-null  object
 23  brch_other  652118 non-null  object
 24  address     652118 non-null  object
 25  zipcode     652118 non-null  int64
 26  zip_city    652118 non-null  object
 27  cb_num      652118 non-null  int64
 28  borocode    652118 non-null  int64
 29  boroname    652118 non-null  object
 30  cncldist    652118 non-null  int64
 31  st_assem    652118 non-null  int64
 32  st_senate   652118 non-null  int64
 33  nta         652118 non-null  object
 34  nta_name    652118 non-null  object
 35  boro_ct     652118 non-null  int64
 36  state       652118 non-null  object
 37  latitude    652118 non-null  float64
 38  longitude   652118 non-null  float64
 39  x_sp        652118 non-null  float64
 40  y_sp        652118 non-null  float64
dtypes: float64(4), int64(11), object(26)
memory usage: 209.0+ MB

In [20]:
# colunms to be dropped potentially ->
# stump_diam, spc_latin, spc_common, steward, problems, root_stone, root_grate, root_other, trunk_wire, 
# trnk_light, brch_shoe, brch_other,

In [40]:
tree_data['zipcode'].value_counts()

106 CROSS BAY BOULEVARD    210
2350 FOREST HILL ROAD      130
2 TELEPORT DRIVE           125
900 SOUTH AVENUE            88
2750 VETERANS ROAD WEST     78
                          ...
26-030 UTOPIA PARKWAY        1
36-031 203 STREET            1
110 NOSTRAND AVENUE          1
116-021 197 STREET           1
209 SOUTH 2 STREET           1
Name: address, Length: 395393, dtype: int64

In [8]:
crime_data = pd.read_csv(r'D:\VTacademics\sem3\urbanComputing\final_project\urban-computing\Data\2015_Crime.csv', low_memory=False)

In [9]:
crime_data.head()

,Ticket Number,Violation Date,Violation Time,Issuing Agency,Respondent First Name,Respondent Last Name,Balance Due,Violation Location (Borough),Violation Location (Block No.),Violation Location (Lot No.),...,Charge #8: Code Description,Charge #8: Infraction Amount,Charge #9: Code,Charge #9: Code Section,Charge #9: Code Description,Charge #9: Infraction Amount,Charge #10: Code,Charge #10: Code Section,Charge #10: Code Description,Charge #10: Infraction Amount
0,0187818290,06/30/2015,07:50:00,SANITATION OTHERS,NaN,607 2 AVE RE,0.0,MANHATTAN,914.0,28.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1276215F1,06/30/2015,NaN,DOHMH - BFSCS,NaN,JEM PROVISIONS INC,NaN,BROOKLYN,NaN,NaN,...,Toilet facility not properly supplied in that ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0700053870,06/30/2015,13:54:00,DEPT OF TRAN,NaN,CONSOLIDATED EDISON,NaN,QUEENS,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0700051990,06/30/2015,14:10:00,DEPT OF TRAN,NaN,CONSOLIDATED EDISON,NaN,QUEENS,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0700051981,06/30/2015,14:04:00,DEPT OF TRANSPORTATION,NaN,CONSOLIDATED EDISON,NaN,QUEENS,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
crime_data.columns

Index(['Ticket Number', 'Violation Date', 'Violation Time', 'Issuing Agency',
       'Respondent First Name', 'Respondent Last Name', 'Balance Due',
       'Violation Location (Borough)', 'Violation Location (Block No.)',
       'Violation Location (Lot No.)', 'Violation Location (House #)',
       'Violation Location (Street Name)', 'Violation Location (Floor)',
       'Violation Location (City)', 'Violation Location (Zip Code)',
       'Violation Location (State Name)', 'Respondent Address (Borough)',
       'Respondent Address (House #)', 'Respondent Address (Street Name)',
       'Respondent Address (City)', 'Respondent Address (Zip Code)',
       'Respondent Address (State Name)', 'Hearing Status', 'Hearing Result',
       'Scheduled Hearing Location', 'Hearing Date', 'Hearing Time',
       'Decision Location (Borough)', 'Decision Date',
       'Total Violation Amount', 'Violation Details', 'Date Judgment Docketed',
       'Respondent Address or Facility Number(For FDNY and DOB Tickets)',
       'Penalty Imposed', 'Paid Amount', 'Additional Penalties or Late Fees',
       'Compliance Status', 'Violation Description', 'Charge #1: Code',
       'Charge #1: Code Section', 'Charge #1: Code Description',
       'Charge #1: Infraction Amount', 'Charge #2: Code',
       'Charge #2: Code Section', 'Charge #2: Code Description',
       'Charge #2: Infraction Amount', 'Charge #3: Code',
       'Charge #3: Code Section', 'Charge #3: Code Description',
       'Charge #3: Infraction Amount', 'Charge #4: Code',
       'Charge #4: Code Section', 'Charge #4: Code Description',
       'Charge #4: Infraction Amount', 'Charge #5: Code',
       'Charge #5: Code Section', 'Charge #5: Code Description',
       'Charge #5: Infraction Amount', 'Charge #6: Code',
       'Charge #6: Code Section', 'Charge #6: Code Description',
       'Charge #6: Infraction Amount', 'Charge #7: Code',
       'Charge #7: Code Section', 'Charge #7: Code Description',
       'Charge #7: Infraction Amount', 'Charge #8: Code',
       'Charge #8: Code Section', 'Charge #8: Code Description',
       'Charge #8: Infraction Amount', 'Charge #9: Code',
       'Charge #9: Code Section', 'Charge #9: Code Description',
       'Charge #9: Infraction Amount', 'Charge #10: Code',
       'Charge #10: Code Section', 'Charge #10: Code Description',
       'Charge #10: Infraction Amount'],
      dtype='object')

In [11]:
crime_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750352 entries, 0 to 750351
Data columns (total 78 columns):
 #   Column                                                           Non-Null Count   Dtype
---  ------                                                           --------------   -----
 0   Ticket Number                                                    750352 non-null  object
 1   Violation Date                                                   750352 non-null  object
 2   Violation Time                                                   611192 non-null  object
 3   Issuing Agency                                                   631478 non-null  object
 4   Respondent First Name                                            348156 non-null  object
 5   Respondent Last Name                                             701497 non-null  object
 6   Balance Due                                                      188781 non-null  float64
 7   Violation Location (Borough)                                     750174 non-null  object
 8   Violation Location (Block No.)                                   553865 non-null  float64
 9   Violation Location (Lot No.)                                     553862 non-null  float64
 10  Violation Location (House #)                                     574440 non-null  object
 11  Violation Location (Street Name)                                 609064 non-null  object
 12  Violation Location (Floor)                                       0 non-null       float64
 13  Violation Location (City)                                        746553 non-null  object
 14  Violation Location (Zip Code)                                    712934 non-null  object
 15  Violation Location (State Name)                                  608048 non-null  object
 16  Respondent Address (Borough)                                     722665 non-null  object
 17  Respondent Address (House #)                                     635149 non-null  object
 18  Respondent Address (Street Name)                                 637034 non-null  object
 19  Respondent Address (City)                                        589957 non-null  object
 20  Respondent Address (Zip Code)                                    588137 non-null  object
 21  Respondent Address (State Name)                                  589829 non-null  object
 22  Hearing Status                                                   611192 non-null  object
 23  Hearing Result                                                   459212 non-null  object
 24  Scheduled Hearing Location                                       610464 non-null  object
 25  Hearing Date                                                     750170 non-null  object
 26  Hearing Time                                                     649036 non-null  object
 27  Decision Location (Borough)                                      161624 non-null  object
 28  Decision Date                                                    567917 non-null  object
 29  Total Violation Amount                                           712441 non-null  float64
 30  Violation Details                                                668429 non-null  object
 31  Date Judgment Docketed                                           130569 non-null  object
 32  Respondent Address or Facility Number(For FDNY and DOB Tickets)  154563 non-null  object
 33  Penalty Imposed                                                  659738 non-null  float64
 34  Paid Amount                                                      627566 non-null  float64
 35  Additional Penalties or Late Fees                                311229 non-null  float64
 36  Compliance Status                                                193953 non-null  object
 37  Violation Description                                            35369 non-null   object
 38  Charge #1: Code                                                  739105 non-null  object
 39  Charge #1: Code Section                                          739066 non-null  object
 40  Charge #1: Code Description                                      637791 non-null  object
 41  Charge #1: Infraction Amount                                     711305 non-null  float64
 42  Charge #2: Code                                                  54411 non-null   object
 43  Charge #2: Code Section                                          54404 non-null   object
 44  Charge #2: Code Description                                      45014 non-null   object
 45  Charge #2: Infraction Amount                                     26715 non-null   float64
 46  Charge #3: Code                                                  38460 non-null   object
 47  Charge #3: Code Section                                          38460 non-null   object
 48  Charge #3: Code Description                                      30075 non-null   object
 49  Charge #3: Infraction Amount                                     13157 non-null   float64
 50  Charge #4: Code                                                  35707 non-null   object
 51  Charge #4: Code Section                                          35707 non-null   object
 52  Charge #4: Code Description                                      27385 non-null   object
 53  Charge #4: Infraction Amount                                     10405 non-null   float64
 54  Charge #5: Code                                                  28199 non-null   object
 55  Charge #5: Code Section                                          28199 non-null   object
 56  Charge #5: Code Description                                      25047 non-null   object
 57  Charge #5: Infraction Amount                                     4046 non-null    float64
 58  Charge #6: Code                                                  27661 non-null   object
 59  Charge #6: Code Section                                          27661 non-null   object
 60  Charge #6: Code Description                                      24531 non-null   object
 61  Charge #6: Infraction Amount                                     3514 non-null    float64
 62  Charge #7: Code                                                  24823 non-null   object
 63  Charge #7: Code Section                                          24823 non-null   object
 64  Charge #7: Code Description                                      21723 non-null   object
 65  Charge #7: Infraction Amount                                     3272 non-null    float64
 66  Charge #8: Code                                                  24631 non-null   object
 67  Charge #8: Code Section                                          24631 non-null   object
 68  Charge #8: Code Description                                      21599 non-null   object
 69  Charge #8: Infraction Amount                                     3083 non-null    float64
 70  Charge #9: Code                                                  19470 non-null   object
 71  Charge #9: Code Section                                          19470 non-null   object
 72  Charge #9: Code Description                                      16463 non-null   object
 73  Charge #9: Infraction Amount                                     3027 non-null    float64
 74  Charge #10: Code                                                 17539 non-null   object
 75  Charge #10: Code Section                                         17539 non-null   object
 76  Charge #10: Code Description                                     16450 non-null   object
 77  Charge #10: Infraction Amount                                    1096 non-null    float64
dtypes: float64(18), object(60)
memory usage: 446.5+ MB

In [12]:
crime_data = crime_data.dropna(subset=['Ticket Number', 'Violation Date', 'Violation Time', 'Issuing Agency',
       'Respondent First Name', 'Respondent Last Name', 'Balance Due',
       'Violation Location (Borough)', 'Violation Location (Block No.)',
       'Violation Location (Lot No.)', 'Violation Location (House #)',
       'Violation Location (Street Name)', 'Violation Location (Floor)',
       'Violation Location (City)', 'Violation Location (Zip Code)',
       'Violation Location (State Name)', 'Respondent Address (Borough)',
       'Respondent Address (House #)', 'Respondent Address (Street Name)',
       'Respondent Address (City)', 'Respondent Address (Zip Code)',
       'Respondent Address (State Name)', 'Hearing Status', 'Hearing Result',
       'Scheduled Hearing Location', 'Hearing Date', 'Hearing Time',
       'Decision Location (Borough)', 'Decision Date',
       'Total Violation Amount', 'Violation Details', 'Date Judgment Docketed',
       'Respondent Address or Facility Number(For FDNY and DOB Tickets)',
       'Penalty Imposed', 'Paid Amount', 'Additional Penalties or Late Fees',
       'Compliance Status', 'Violation Description', 'Charge #1: Code',
       'Charge #1: Code Section', 'Charge #1: Code Description',
       'Charge #1: Infraction Amount', 'Charge #2: Code',
       'Charge #2: Code Section', 'Charge #2: Code Description',
       'Charge #2: Infraction Amount', 'Charge #3: Code',
       'Charge #3: Code Section', 'Charge #3: Code Description',
       'Charge #3: Infraction Amount', 'Charge #4: Code',
       'Charge #4: Code Section', 'Charge #4: Code Description',
       'Charge #4: Infraction Amount', 'Charge #5: Code',
       'Charge #5: Code Section', 'Charge #5: Code Description',
       'Charge #5: Infraction Amount', 'Charge #6: Code',
       'Charge #6: Code Section', 'Charge #6: Code Description',
       'Charge #6: Infraction Amount', 'Charge #7: Code',
       'Charge #7: Code Section', 'Charge #7: Code Description',
       'Charge #7: Infraction Amount', 'Charge #8: Code',
       'Charge #8: Code Section', 'Charge #8: Code Description',
       'Charge #8: Infraction Amount', 'Charge #9: Code',
       'Charge #9: Code Section', 'Charge #9: Code Description',
       'Charge #9: Infraction Amount', 'Charge #10: Code',
       'Charge #10: Code Section', 'Charge #10: Code Description',
       'Charge #10: Infraction Amount'])

In [13]:
crime_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 78 columns):
 #   Column                                                           Non-Null Count  Dtype
---  ------                                                           --------------  -----
 0   Ticket Number                                                    0 non-null      object
 1   Violation Date                                                   0 non-null      object
 2   Violation Time                                                   0 non-null      object
 3   Issuing Agency                                                   0 non-null      object
 4   Respondent First Name                                            0 non-null      object
 5   Respondent Last Name                                             0 non-null      object
 6   Balance Due                                                      0 non-null      float64
 7   Violation Location (Borough)                                     0 non-null      object
 8   Violation Location (Block No.)                                   0 non-null      float64
 9   Violation Location (Lot No.)                                     0 non-null      float64
 10  Violation Location (House #)                                     0 non-null      object
 11  Violation Location (Street Name)                                 0 non-null      object
 12  Violation Location (Floor)                                       0 non-null      float64
 13  Violation Location (City)                                        0 non-null      object
 14  Violation Location (Zip Code)                                    0 non-null      object
 15  Violation Location (State Name)                                  0 non-null      object
 16  Respondent Address (Borough)                                     0 non-null      object
 17  Respondent Address (House #)                                     0 non-null      object
 18  Respondent Address (Street Name)                                 0 non-null      object
 19  Respondent Address (City)                                        0 non-null      object
 20  Respondent Address (Zip Code)                                    0 non-null      object
 21  Respondent Address (State Name)                                  0 non-null      object
 22  Hearing Status                                                   0 non-null      object
 23  Hearing Result                                                   0 non-null      object
 24  Scheduled Hearing Location                                       0 non-null      object
 25  Hearing Date                                                     0 non-null      object
 26  Hearing Time                                                     0 non-null      object
 27  Decision Location (Borough)                                      0 non-null      object
 28  Decision Date                                                    0 non-null      object
 29  Total Violation Amount                                           0 non-null      float64
 30  Violation Details                                                0 non-null      object
 31  Date Judgment Docketed                                           0 non-null      object
 32  Respondent Address or Facility Number(For FDNY and DOB Tickets)  0 non-null      object
 33  Penalty Imposed                                                  0 non-null      float64
 34  Paid Amount                                                      0 non-null      float64
 35  Additional Penalties or Late Fees                                0 non-null      float64
 36  Compliance Status                                                0 non-null      object
 37  Violation Description                                            0 non-null      object
 38  Charge #1: Code                                                  0 non-null      object
 39  Charge #1: Code Section                                          0 non-null      object
 40  Charge #1: Code Description                                      0 non-null      object
 41  Charge #1: Infraction Amount                                     0 non-null      float64
 42  Charge #2: Code                                                  0 non-null      object
 43  Charge #2: Code Section                                          0 non-null      object
 44  Charge #2: Code Description                                      0 non-null      object
 45  Charge #2: Infraction Amount                                     0 non-null      float64
 46  Charge #3: Code                                                  0 non-null      object
 47  Charge #3: Code Section                                          0 non-null      object
 48  Charge #3: Code Description                                      0 non-null      object
 49  Charge #3: Infraction Amount                                     0 non-null      float64
 50  Charge #4: Code                                                  0 non-null      object
 51  Charge #4: Code Section                                          0 non-null      object
 52  Charge #4: Code Description                                      0 non-null      object
 53  Charge #4: Infraction Amount                                     0 non-null      float64
 54  Charge #5: Code                                                  0 non-null      object
 55  Charge #5: Code Section                                          0 non-null      object
 56  Charge #5: Code Description                                      0 non-null      object
 57  Charge #5: Infraction Amount                                     0 non-null      float64
 58  Charge #6: Code                                                  0 non-null      object
 59  Charge #6: Code Section                                          0 non-null      object
 60  Charge #6: Code Description                                      0 non-null      object
 61  Charge #6: Infraction Amount                                     0 non-null      float64
 62  Charge #7: Code                                                  0 non-null      object
 63  Charge #7: Code Section                                          0 non-null      object
 64  Charge #7: Code Description                                      0 non-null      object
 65  Charge #7: Infraction Amount                                     0 non-null      float64
 66  Charge #8: Code                                                  0 non-null      object
 67  Charge #8: Code Section                                          0 non-null      object
 68  Charge #8: Code Description                                      0 non-null      object
 69  Charge #8: Infraction Amount                                     0 non-null      float64
 70  Charge #9: Code                                                  0 non-null      object
 71  Charge #9: Code Section                                          0 non-null      object
 72  Charge #9: Code Description                                      0 non-null      object
 73  Charge #9: Infraction Amount                                     0 non-null      float64
 74  Charge #10: Code                                                 0 non-null      object
 75  Charge #10: Code Section                                         0 non-null      object
 76  Charge #10: Code Description                                     0 non-null      object
 77  Charge #10: Infraction Amount                                    0 non-null      float64
dtypes: float64(18), object(60)
memory usage: 0.0+ bytes

Empty DataFrame
Columns: [Ticket Number, Violation Date, Violation Time, Issuing Agency, Respondent First Name, Respondent Last Name, Balance Due, Violation Location (Borough), Violation Location (Block No.), Violation Location (Lot No.), Violation Location (House #), Violation Location (Street Name), Violation Location (Floor), Violation Location (City), Violation Location (Zip Code), Violation Location (State Name), Respondent Address (Borough), Respondent Address (House #), Respondent Address (Street Name), Respondent Address (City), Respondent Address (Zip Code), Respondent Address (State Name), Hearing Status, Hearing Result, Scheduled Hearing Location, Hearing Date, Hearing Time, Decision Location (Borough), Decision Date, Total Violation Amount, Violation Details, Date Judgment Docketed, Respondent Address or Facility Number(For FDNY and DOB Tickets), Penalty Imposed, Paid Amount, Additional Penalties or Late Fees, Compliance Status, Violation Description, Charge #1: Code, Charge #1: Code Section, Charge #1: Code Description, Charge #1: Infraction Amount, Charge #2: Code, Charge #2: Code Section, Charge #2: Code Description, Charge #2: Infraction Amount, Charge #3: Code, Charge #3: Code Section, Charge #3: Code Description, Charge #3: Infraction Amount, Charge #4: Code, Charge #4: Code Section, Charge #4: Code Description, Charge #4: Infraction Amount, Charge #5: Code, Charge #5: Code Section, Charge #5: Code Description, Charge #5: Infraction Amount, Charge #6: Code, Charge #6: Code Section, Charge #6: Code Description, Charge #6: Infraction Amount, Charge #7: Code, Charge #7: Code Section, Charge #7: Code Description, Charge #7: Infraction Amount, Charge #8: Code, Charge #8: Code Section, Charge #8: Code Description, Charge #8: Infraction Amount, Charge #9: Code, Charge #9: Code Section, Charge #9: Code Description, Charge #9: Infraction Amount, Charge #10: Code, Charge #10: Code Section, Charge #10: Code Description, Charge #10: Infraction Amount]
Index: []

[0 rows x 78 columns]